name: React action
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Get the code
      uses: actions/checkout@v3
    - name: Install all dependencies
      run: npm ci 
    - name: Build the app
      run: npm run build
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build # The folder the action should deploy.
